name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
      - name: Setup Acton
        uses: actonlang/setup-acton

      - name: Build Project
        run: acton build

      - name: Run Tests
        run: acton test
