name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actonlang/setup-acton@v2

      - name: Build Project
        run: acton build

      - name: Run Tests
        run: acton test
